version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "4001:3000"
    volumes:
      - /home/node/app/node_modules # bookmark (don't map outside)
      - .:/home/node/app # (map current folder outside container to app folder inside)
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules # bookmark (don't map outside)
      - .:/home/node/app # (map current folder outside container to app folder inside)
    command: ["npm", "run", "test"]